
export const abbreviationData = {
  "8급~6급 (기초 생활 한자)": [
    { "standard": "國", "abbreviation": "国", "hun": "나라", "eum": "국" },
    { "standard": "學", "abbreviation": "学", "hun": "배울", "eum": "학" },
    { "standard": "萬", "abbreviation": "万", "hun": "일만", "eum": "만" },
    { "standard": "圖", "abbreviation": "図", "hun": "그림", "eum": "도" },
    { "standard": "禮", "abbreviation": "礼", "hun": "예도", "eum": "례" },
    { "standard": "區", "abbreviation": "区", "hun": "구분할", "eum": "구" },
    { "standard": "氣", "abbreviation": "気", "hun": "기운", "eum": "기" },
    { "standard": "晝", "abbreviation": "昼", "hun": "낮", "eum": "주" },
    { "standard": "個", "abbreviation": "个", "hun": "낱", "eum": "개" },
    { "standard": "畫", "abbreviation": "画", "hun": "그림", "eum": "화" },
    { "standard": "無", "abbreviation": "无", "hun": "없을", "eum": "무" },
    { "standard": "賣", "abbreviation": "売", "hun": "팔", "eum": "매" },
    { "standard": "會", "abbreviation": "会", "hun": "모일", "eum": "회" },
    { "standard": "步", "abbreviation": "歩", "hun": "걸음", "eum": "보" },
    { "standard": "和", "abbreviation": "咊", "hun": "화할", "eum": "화" }
  ],
  "5급~4급 (중급 빈출 한자)": [
    { "standard": "對", "abbreviation": "対", "hun": "대답할", "eum": "대" },
    { "standard": "體", "abbreviation": "体", "hun": "몸", "eum": "체" },
    { "standard": "實", "abbreviation": "実", "hun": "열매/참", "eum": "실" },
    { "standard": "鐵", "abbreviation": "鉄", "hun": "쇠", "eum": "철" },
    { "standard": "獨", "abbreviation": "独", "hun": "홀로", "eum": "독" },
    { "standard": "醫", "abbreviation": "医", "hun": "의원", "eum": "의" },
    { "standard": "戰", "abbreviation": "戦", "hun": "싸움", "eum": "전" },
    { "standard": "廣", "abbreviation": "広", "hun": "넓을", "eum": "광" },
    { "standard": "舊", "abbreviation": "旧", "hun": "예/오래될", "eum": "구" },
    { "standard": "數", "abbreviation": "数", "hun": "셀/수", "eum": "수" },
    { "standard": "發", "abbreviation": "発", "hun": "필", "eum": "발" },
    { "standard": "兩", "abbreviation": "両", "hun": "두", "eum": "량" },
    { "standard": "當", "abbreviation": "当", "hun": "당할", "eum": "당" },
    { "standard": "勞", "abbreviation": "労", "hun": "일할", "eum": "로" },
    { "standard": "號", "abbreviation": "号", "hun": "이름/부를", "eum": "호" },
    { "standard": "價", "abbreviation": "価", "hun": "값", "eum": "가" },
    { "standard": "團", "abbreviation": "団", "hun": "둥글", "eum": "단" },
    { "standard": "溫", "abbreviation": "温", "hun": "따뜻할", "eum": "온" },
    { "standard": "惡", "abbreviation": "悪", "hun": "악할", "eum": "악" },
    { "standard": "黃", "abbreviation": "黄", "hun": "누를", "eum": "황" }
  ],
  "3급 (공인급수 필수)": [
    { "standard": "關", "abbreviation": "関", "hun": "관계할", "eum": "관" },
    { "standard": "觀", "abbreviation": "観", "hun": "볼", "eum": "관" },
    { "standard": "斷", "abbreviation": "断", "hun": "끊을", "eum": "단" },
    { "standard": "變", "abbreviation": "変", "hun": "변할", "eum": "변" },
    { "standard": "證", "abbreviation": "証", "hun": "증거", "eum": "증" },
    { "standard": "譯", "abbreviation": "訳", "hun": "번역할", "eum": "역" },
    { "standard": "險", "abbreviation": "険", "hun": "험할", "eum": "험" },
    { "standard": "顯", "abbreviation": "顕", "hun": "나타날", "eum": "현" },
    { "standard": "寫", "abbreviation": "写", "hun": "베낄", "eum": "사" },
    { "standard": "應", "abbreviation": "応", "hun": "응할", "eum": "응" },
    { "standard": "藝", "abbreviation": "芸", "hun": "심을/재주", "eum": "예" },
    { "standard": "辭", "abbreviation": "辞", "hun": "말씀", "eum": "사" },
    { "standard": "處", "abbreviation": "処", "hun": "곳", "eum": "처" },
    { "standard": "廳", "abbreviation": "庁", "hun": "관청", "eum": "청" },
    { "standard": "擇", "abbreviation": "択", "hun": "가릴", "eum": "택" },
    { "standard": "廢", "abbreviation": "廃", "hun": "폐할", "eum": "폐" },
    { "standard": "豊", "abbreviation": "豊", "hun": "풍성할", "eum": "풍" },
    { "standard": "縣", "abbreviation": "県", "hun": "고을", "eum": "현" },
    { "standard": "惠", "abbreviation": "恵", "hun": "은혜", "eum": "혜" },
    { "standard": "黑", "abbreviation": "黒", "hun": "검을", "eum": "흑" }
  ],
  "2급~1급 (전문 약자)": [
    { "standard": "價", "abbreviation": "価", "hun": "값", "eum": "가" },
    { "standard": "假", "abbreviation": "仮", "hun": "거짓", "eum": "가" },
    { "standard": "覺", "abbreviation": "覚", "hun": "깨달을", "eum": "각" },
    { "standard": "檢", "abbreviation": "検", "hun": "검사할", "eum": "검" },
    { "standard": "擊", "abbreviation": "撃", "hun": "칠", "eum": "격" },
    { "standard": "繼", "abbreviation": "継", "hun": "이을", "eum": "계" },
    { "standard": "權", "abbreviation": "権", "hun": "권세", "eum": "권" },
    { "standard": "歸", "abbreviation": "帰", "hun": "돌아갈", "eum": "귀" },
    { "standard": "讀", "abbreviation": "読", "hun": "읽을", "eum": "독" },
    { "standard": "亂", "abbreviation": "乱", "hun": "어지러울", "eum": "란" },
    { "standard": "寫", "abbreviation": "写", "hun": "베낄", "eum": "사" },
    { "standard": "釋", "abbreviation": "釈", "hun": "풀", "eum": "석" },
    { "standard": "樣", "abbreviation": "様", "hun": "모양", "eum": "양" },
    { "standard": "與", "abbreviation": "与", "hun": "더불어", "eum": "여" },
    { "standard": "榮", "abbreviation": "栄", "hun": "영화", "eum": "영" },
    { "standard": "營", "abbreviation": "営", "hun": "경영할", "eum": "영" },
    { "standard": "驛", "abbreviation": "駅", "hun": "역", "eum": "역" },
    { "standard": "圓", "abbreviation": "円", "hun": "둥글", "eum": "원" },
    { "standard": "讓", "abbreviation": "譲", "hun": "사양할", "eum": "양" },
    { "standard": "鹽", "abbreviation": "塩", "hun": "소금", "eum": "염" },
    { "standard": "龍", "abbreviation": "竜", "hun": "용", "eum": "룡" },
    { "standard": "壘", "abbreviation": "塁", "hun": "보루", "eum": "루" },
    { "standard": "默", "abbreviation": "黙", "hun": "잠잠할", "eum": "묵" },
    { "standard": "聲", "abbreviation": "声", "hun": "소리", "eum": "성" },
    { "standard": "濕", "abbreviation": "湿", "hun": "축축할", "eum": "습" },
    { "standard": "亞", "abbreviation": "亜", "hun": "버금", "eum": "아" },
    { "standard": "奧", "abbreviation": "奥", "hun": "깊을", "eum": "오" },
    { "standard": "壓", "abbreviation": "圧", "hun": "누를", "eum": "압" },
    { "standard": "劑", "abbreviation": "剤", "hun": "약조절할", "eum": "제" },
    { "standard": "濟", "abbreviation": "済", "hun": "건널", "eum": "제" }
  ]
};
