
export const wordData = {
    "8급": [
        { "hanja": "學校", "eum": "학교", "meaning": "학생들이 공부하는 곳." },
        { "hanja": "韓國", "eum": "한국", "meaning": "대한민국의 줄임말." },
        { "hanja": "父母", "eum": "부모", "meaning": "아버지와 어머니." },
        { "hanja": "兄弟", "eum": "형제", "meaning": "형과 아우." },
        { "hanja": "先生", "eum": "선생", "meaning": "가르침을 주는 사람." },
        { "hanja": "學生", "eum": "학생", "meaning": "배우는 사람." },
        { "hanja": "男女", "eum": "남녀", "meaning": "남자와 여자." },
        { "hanja": "山川", "eum": "산천", "meaning": "산과 시내." },
        { "hanja": "日月", "eum": "일월", "meaning": "해와 달, 또는 세월." },
        { "hanja": "大小", "eum": "대소", "meaning": "큼과 작음." },
        { "hanja": "上下", "eum": "상하", "meaning": "위와 아래." },
        { "hanja": "長短", "eum": "장단", "meaning": "길고 짧음." },
        { "hanja": "靑山", "eum": "청산", "meaning": "푸른 산." },
        { "hanja": "白雪", "eum": "백설", "meaning": "흰 눈." },
        { "hanja": "水火", "eum": "수화", "meaning": "물과 불." },
        { "hanja": "木手", "eum": "목수", "meaning": "나무를 다루는 기술자." },
        { "hanja": "土木", "eum": "토목", "meaning": "흙과 나무, 공사 관련 일." },
        { "hanja": "千金", "eum": "천금", "meaning": "아주 많은 돈." },
        { "hanja": "萬一", "eum": "만일", "meaning": "혹시 있을지도 모르는 상황." },
        { "hanja": "人力", "eum": "인력", "meaning": "사람의 힘." },
        { "hanja": "六月", "eum": "유월", "meaning": "여섯 번째 달." },
        { "hanja": "八道", "eum": "팔도", "meaning": "우리나라 전체 땅." },
        { "hanja": "九十", "eum": "구십", "meaning": "아흔." },
        { "hanja": "十字", "eum": "십자", "meaning": "열 십 자 모양." },
        { "hanja": "東西", "eum": "동서", "meaning": "동쪽과 서쪽." },
        { "hanja": "南北", "eum": "남북", "meaning": "남쪽과 북쪽." },
        { "hanja": "王室", "eum": "왕실", "meaning": "임금의 집안." },
        { "hanja": "空中", "eum": "공중", "meaning": "허공의 가운데." },
        { "hanja": "寸劇", "eum": "촌극", "meaning": "아주 짧은 연극." },
        { "hanja": "年生", "eum": "년생", "meaning": "태어난 해를 나타내는 말." }
    ],
    "준7급":[
        { "hanja": "歌謠", "eum": "가요", "meaning": "대중적으로 널리 부르는 노래." },
      { "hanja": "工場", "eum": "공장", "meaning": "물품을 제조하는 곳." },
      { "hanja": "交通", "eum": "교통", "meaning": "차나 배 등이 오가는 일." },
      { "hanja": "氣分", "eum": "기분", "meaning": "마음의 상태나 분위기." },
      { "hanja": "道路", "eum": "도로", "meaning": "사람이나 차가 다니는 길." },
      { "hanja": "冬至", "eum": "동지", "meaning": "밤이 가장 긴 절기." },
      { "hanja": "萬歲", "eum": "만세", "meaning": "축복하거나 승리를 외치는 소리." },
      { "hanja": "物件", "eum": "물건", "meaning": "구체적인 형태가 있는 물체." },
      { "hanja": "美術", "eum": "미술", "meaning": "공간이나 형상을 꾸미는 예술." },
      { "hanja": "方向", "eum": "방향", "meaning": "나아가는 쪽." },
      { "hanja": "父母", "eum": "부모", "meaning": "아버지와 어머니." },
      { "hanja": "事建", "eum": "사건", "meaning": "일어난 일." },
      { "hanja": "市場", "eum": "시장", "meaning": "물건을 사고파는 장소." },
      { "hanja": "食品", "eum": "식품", "meaning": "사람이 먹을 수 있게 만든 것." },
      { "hanja": "新聞", "eum": "신문", "meaning": "새 소식을 알리는 정기간행물." },
      { "hanja": "夜間", "eum": "야간", "meaning": "밤 사이의 시간." },
      { "hanja": "藥局", "eum": "약국", "meaning": "약을 지어 파는 곳." },
      { "hanja": "餘暇", "eum": "여가", "meaning": "남는 시간이나 짬." },
      { "hanja": "永遠", "eum": "영원", "meaning": "끝없이 이어지는 시간." },
      { "hanja": "五福", "eum": "오복", "meaning": "사람이 누리는 다섯 가지 복." },
      { "hanja": "勇氣", "eum": "용기", "meaning": "씩씩하고 굳센 기운." },
      { "hanja": "宇宙", "eum": "우주", "meaning": "만물이 존재하는 끝없는 공간." },
      { "hanja": "雲海", "eum": "운해", "meaning": "구름이 바다처럼 깔린 모습." },
      { "hanja": "注意", "eum": "주의", "meaning": "마음을 집중하여 살핌." },
      { "hanja": "中央", "eum": "중앙", "meaning": "가운데 부분." },
      { "hanja": "直行", "eum": "직행", "meaning": "중간에 들르지 않고 바로 감." },
      { "hanja": "天下", "eum": "천하", "meaning": "하늘 아래 온 세상." },
      { "hanja": "親舊", "eum": "친구", "meaning": "가깝게 오래 사귄 사람." },
      { "hanja": "平和", "eum": "평화", "meaning": "화목하고 평온한 상태." },
      { "hanja": "漢江", "eum": "한강", "meaning": "한국의 대표적인 강 이름." }
    ],
    "7급": [
        { "hanja": "工夫", "eum": "공부", "meaning": "학문을 배우고 익힘." },
        { "hanja": "回答", "eum": "회답", "meaning": "물음에 대답함." },
        { "hanja": "日記", "eum": "일기", "meaning": "날마다 기록하는 글." },
        { "hanja": "江山", "eum": "강산", "meaning": "강과 산, 자연의 풍경." },
        { "hanja": "空氣", "eum": "공기", "meaning": "숨 쉬는 데 필요한 기체." },
        { "hanja": "農村", "eum": "농촌", "meaning": "농사짓는 사람들이 사는 마을." },
        { "hanja": "軍人", "eum": "군인", "meaning": "나라를 지키는 사람." },
        { "hanja": "正月", "eum": "정월", "meaning": "한 해의 첫째 달." },
        { "hanja": "住所", "eum": "주소", "meaning": "살고 있는 장소." },
        { "hanja": "市場", "eum": "시장", "meaning": "물건을 사고파는 곳." },
        { "hanja": "文明", "eum": "문명", "meaning": "발달한 인류 사회의 상태." },
        { "hanja": "花園", "eum": "화원", "meaning": "꽃밭." },
        { "hanja": "草木", "eum": "초목", "meaning": "풀과 나무." },
        { "hanja": "食口", "eum": "식구", "meaning": "함께 밥을 먹는 가족." },
        { "hanja": "名山", "eum": "명산", "meaning": "이름난 유명한 산." },
        { "hanja": "邑面", "eum": "읍면", "meaning": "지방 행정 구역의 이름." },
        { "hanja": "休日", "eum": "휴일", "meaning": "쉬는 날." },
        { "hanja": "生活", "eum": "생활", "meaning": "살아 나가는 활동." },
        { "hanja": "市民", "eum": "시민", "meaning": "도시에 사는 사람." },
        { "hanja": "出入", "eum": "출입", "meaning": "나가고 들어옴." },
        { "hanja": "門前", "eum": "문전", "meaning": "문 앞." },
        { "hanja": "後門", "eum": "후문", "meaning": "뒷문." },
        { "hanja": "平日", "eum": "평일", "meaning": "일요일과 공휴일을 제외한 날." },
        { "hanja": "午後", "eum": "오후", "meaning": "낮 열두 시부터 밤까지." },
        { "hanja": "午前", "eum": "오전", "meaning": "밤 열두 시부터 낮까지." },
        { "hanja": "心身", "eum": "심신", "meaning": "마음과 몸." },
        { "hanja": "全體", "eum": "전체", "meaning": "모든 부분." },
        { "hanja": "每日", "eum": "매일", "meaning": "날마다." },
        { "hanja": "自身", "eum": "자신", "meaning": "자기 몸이나 스스로." },
        { "hanja": "近日", "eum": "근일", "meaning": "가까운 며칠 사이." }
    ],
    "준6급": [
        { "hanja": "感謝", "eum": "감사", "meaning": "고맙게 여기는 마음." },
      { "hanja": "決心", "eum": "결심", "meaning": "마음을 굳게 정함." },
      { "hanja": "公園", "eum": "공원", "meaning": "시민들이 쉬도록 꾸민 정원." },
      { "hanja": "科學", "eum": "과학", "meaning": "법칙을 연구하는 학문." },
      { "hanja": "敎育", "eum": "교육", "meaning": "가르치고 길러내는 일." },
      { "hanja": "九重", "eum": "구중", "meaning": "겹겹이 깊이 들어간 곳." },
      { "hanja": "祈禱", "eum": "기도", "meaning": "신에게 비는 일." },
      { "hanja": "農事", "eum": "농사", "meaning": "곡식을 심어 가꾸는 일." },
      { "hanja": "單純", "eum": "단순", "meaning": "복잡하지 않고 간단함." },
      { "hanja": "對話", "eum": "대화", "meaning": "서로 마주 보고 주고받는 말." },
      { "hanja": "都市", "eum": "도시", "meaning": "사람이 많이 사는 중심지." },
      { "hanja": "名譽", "eum": "명예", "meaning": "이름난 영광스러운 가치." },
      { "hanja": "文明", "eum": "문명", "meaning": "지혜와 기술이 발달한 상태." },
      { "hanja": "放送", "eum": "방송", "meaning": "전파를 이용해 소식을 전함." },
      { "hanja": "報告", "eum": "보고", "meaning": "알아야 할 내용을 알림." },
      { "hanja": "事實", "eum": "사실", "meaning": "실제로 있었던 일." },
      { "hanja": "思想", "eum": "사상", "meaning": "어떤 사물에 대한 생각." },
      { "hanja": "先祖", "eum": "선조", "meaning": "조상의 윗대 어른." },
      { "hanja": "世界", "eum": "세계", "meaning": "지구상의 모든 나라." },
      { "hanja": "信賴", "eum": "신뢰", "meaning": "믿고 의지함." },
      { "hanja": "約束", "eum": "약속", "meaning": "지키기로 정한 말." },
      { "hanja": "歷史", "eum": "역사", "meaning": "인류 사회의 과거 기록." },
      { "hanja": "勇敢", "eum": "용감", "meaning": "용기가 있고 씩씩함." },
      { "hanja": "運命", "eum": "운명", "meaning": "결정되어 있는 삶의 흐름." },
      { "hanja": "遺物", "eum": "유물", "meaning": "과거 사람이 남긴 물건." },
      { "hanja": "自由", "eum": "자유", "meaning": "구속받지 않는 상태." },
      { "hanja": "精神", "eum": "정신", "meaning": "마음의 작용이나 기운." },
      { "hanja": "尊重", "eum": "존중", "meaning": "높여 귀하게 여김." },
      { "hanja": "親切", "eum": "친절", "meaning": "다정하고 정성스러움." },
      { "hanja": "幸福", "eum": "행복", "meaning": "즐겁고 만족스러운 상태." }
    ],
    "6급": [
        { "hanja": "運動", "eum": "운동", "meaning": "건강을 위해 몸을 움직임." },
        { "hanja": "注意", "eum": "주의", "meaning": "마음을 집중하여 살핌." },
        { "hanja": "健康", "eum": "건강", "meaning": "몸이 튼튼하고 탈이 없음." },
        { "hanja": "希望", "eum": "희망", "meaning": "기대를 가지고 바람." },
        { "hanja": "理由", "eum": "이유", "meaning": "어떠한 일의 까닭." },
        { "hanja": "平和", "eum": "평화", "meaning": "전쟁 없는 온화한 상태." },
        { "hanja": "自然", "eum": "자연", "meaning": "인위적이지 않은 본래의 모습." },
        { "hanja": "世界", "eum": "세계", "meaning": "지구상의 모든 나라." },
        { "hanja": "放送", "eum": "방송", "meaning": "전파를 통해 전함." },
        { "hanja": "勇氣", "eum": "용기", "meaning": "씩씩하고 굳센 기운." },
        { "hanja": "幸福", "eum": "행복", "meaning": "기쁘고 즐거운 상태." },
        { "hanja": "特別", "eum": "특별", "meaning": "보통과 아주 다름." },
        { "hanja": "約束", "eum": "약속", "meaning": "서로 정하여 어기지 않기로 함." },
        { "hanja": "勝利", "eum": "승리", "meaning": "싸움에서 이김." },
        { "hanja": "禮儀", "eum": "예의", "meaning": "지켜야 할 도리나 예절." },
        { "hanja": "愛國", "eum": "애국", "meaning": "나라를 사랑함." },
        { "hanja": "感謝", "eum": "감사", "meaning": "고맙게 여김." },
        { "hanja": "表情", "eum": "표정", "meaning": "마음이 얼굴에 나타남." },
        { "hanja": "尊敬", "eum": "존경", "meaning": "높여 우러러봄." },
        { "hanja": "音樂", "eum": "음악", "meaning": "소리를 소재로 하는 예술." },
        { "hanja": "計算", "eum": "계산", "meaning": "수를 세거나 따짐." },
        { "hanja": "發展", "eum": "발전", "meaning": "더 낫게 나아감." },
        { "hanja": "親切", "eum": "친절", "meaning": "정답고 정성스러움." },
        { "hanja": "準備", "eum": "준비", "meaning": "미리 마련하여 갖춤." },
        { "hanja": "發見", "eum": "발견", "meaning": "찾아내지 못한 것을 찾아냄." },
        { "hanja": "工場", "eum": "공장", "meaning": "물건을 만드는 곳." },
        { "hanja": "敎室", "eum": "교실", "meaning": "학생들이 수업하는 방." },
        { "hanja": "圖書館", "eum": "도서관", "meaning": "책을 모아 두고 읽는 곳." },
        { "hanja": "新聞", "eum": "신문", "meaning": "새로운 소식을 알리는 종이." },
        { "hanja": "病院", "eum": "병원", "meaning": "환자를 치료하는 곳." }
    ],
    "준5급":[
        { "hanja": "經濟", "eum": "경제", "meaning": "물건을 생산하고 소비하는 활동." },
      { "hanja": "慶事", "eum": "경사", "meaning": "경사스럽고 기쁜 일." },
      { "hanja": "廣告", "eum": "광고", "meaning": "널리 알리는 일." },
      { "hanja": "技術", "eum": "기술", "meaning": "만드는 재주나 방법." },
      { "hanja": "努力", "eum": "노력", "meaning": "애를 써서 힘을 들임." },
      { "hanja": "團體", "eum": "단체", "meaning": "목적이 같은 여럿의 모임." },
      { "hanja": "大統領", "eum": "대통령", "meaning": "한 나라의 최고 통치자." },
      { "hanja": "登校", "eum": "등교", "meaning": "학교에 감." },
      { "hanja": "矛盾", "eum": "모순", "meaning": "앞뒤가 맞지 않음." },
      { "hanja": "貿易", "eum": "무역", "meaning": "나라 사이에 물건을 사고팜." },
      { "hanja": "法律", "eum": "법률", "meaning": "사회 규범이자 강제 규칙." },
      { "hanja": "補習", "eum": "보습", "meaning": "부족한 공부를 보충함." },
      { "hanja": "服從", "eum": "복종", "meaning": "명령에 그대로 따름." },
      { "hanja": "比較", "eum": "비교", "meaning": "서로 견주어 봄." },
      { "hanja": "思想", "eum": "사상", "meaning": "사물에 대한 체계적 생각." },
      { "hanja": "誠實", "eum": "성실", "meaning": "정성스럽고 참됨." },
      { "hanja": "失敗", "eum": "실패", "meaning": "원하는 목적을 못 이룸." },
      { "hanja": "藝術", "eum": "예술", "meaning": "아름다움을 표현하는 활동." },
      { "hanja": "溫道", "eum": "온도", "meaning": "덥고 차가운 정도." },
      { "hanja": "依支", "eum": "의지", "meaning": "믿고 기댐." },
      { "hanja": "人格", "eum": "인격", "meaning": "사람의 품격." },
      { "hanja": "責任", "eum": "책임", "meaning": "맡아서 해야 할 의무." },
      { "hanja": "淸潔", "eum": "청결", "meaning": "맑고 깨끗함." },
      { "hanja": "祝賀", "eum": "축하", "meaning": "기쁜 일을 즐거워함." },
      { "hanja": "親和", "eum": "친화", "meaning": "서로 사이좋게 지냄." },
      { "hanja": "通知", "eum": "통지", "meaning": "기별하여 알림." },
      { "hanja": "特別", "eum": "특별", "meaning": "보통과 아주 다름." },
      { "hanja": "表示", "eum": "표시", "meaning": "겉으로 나타냄." },
      { "hanja": "合意", "eum": "합의", "meaning": "의견이 일치함." },
      { "hanja": "希望", "eum": "희망", "meaning": "바라는 기대." }
    ],
    "5급":[
        { "hanja": "佳約", "eum": "가약", "meaning": "아름다운 약속, 주로 혼인." },
        { "hanja": "觀察", "eum": "관찰", "meaning": "주의 깊게 살핌." },
        { "hanja": "窮極", "eum": "궁극", "meaning": "마지막의 끝." },
        { "hanja": "貴重", "eum": "귀중", "meaning": "귀하고 소중함." },
        { "hanja": "給食", "eum": "급식", "meaning": "음식을 나누어 줌." },
        { "hanja": "勤勉", "eum": "근면", "meaning": "부지런히 일함." },
        { "hanja": "期待", "eum": "기대", "meaning": "바라고 기다림." },
        { "hanja": "念願", "eum": "염원", "meaning": "간절히 바라는 마음." },
        { "hanja": "能率", "eum": "능률", "meaning": "일의 성과가 나는 정도." },
        { "hanja": "道德", "eum": "도덕", "meaning": "사람으로서 지켜야 할 도리." },
        { "hanja": "獨立", "eum": "독립", "meaning": "남에게 의지하지 않고 섬." },
        { "hanja": "名答", "eum": "명답", "meaning": "명쾌하고 훌륭한 대답." },
        { "hanja": "貿易", "eum": "무역", "meaning": "국가 간의 상거래." },
        { "hanja": "發見", "eum": "발견", "meaning": "미처 몰랐던 것을 찾아냄." },
        { "hanja": "煩悶", "eum": "번민", "meaning": "마음이 답답해 괴로워함." },
        { "hanja": "報酬", "eum": "보수", "meaning": "일한 대가로 받는 돈." },
        { "hanja": "復習", "eum": "복습", "meaning": "배운 것을 다시 공부함." },
        { "hanja": "奉仕", "eum": "봉사", "meaning": "남을 위해 애씀." },
        { "hanja": "象徵", "eum": "상징", "meaning": "추상적인 것을 구체적으로 나타냄." },
        { "hanja": "先導", "eum": "선도", "meaning": "앞장서서 이끎." },
        { "hanja": "習慣", "eum": "습관", "meaning": "몸에 밴 버릇." },
        { "hanja": "迎接", "eum": "영접", "meaning": "손님을 맞이함." },
        { "hanja": "勇退", "eum": "용퇴", "meaning": "용기 있게 물러남." },
        { "hanja": "恩惠", "eum": "은혜", "meaning": "고맙게 베풀어 주는 혜택." },
        { "hanja": "忍耐", "eum": "인내", "meaning": "괴로움을 참고 견딤." },
        { "hanja": "慈悲", "eum": "자비", "meaning": "사랑하고 가엾게 여김." },
        { "hanja": "精誠", "eum": "정성", "meaning": "참되고 지극한 마음." },
        { "hanja": "尊重", "eum": "존중", "meaning": "귀하게 여겨 받듦." },
        { "hanja": "智惠", "eum": "지혜", "meaning": "사물을 깨닫고 판단하는 힘." },
        { "hanja": "和合", "eum": "화합", "meaning": "화목하게 어울림." }
    ]
};
